[package]
name = "cirith-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
sqlx = {version = "0.8", features = ["runtime-tokio", "sqlite"]}
sha2 = "0.10"
thiserror = "2"
tracing = "0.1"
url = "2.5.7"